# source bashrc
if [ -f $HOME/.bashrc ]; then
        source $HOME/.bashrc
fi

# Load shell dotfiles
for file in ~/.{path,bash_prompt,aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

echo "Loading NVM"
echo `date`
# NVM
# Putting NVM load here since it takes a very long time
export NVM_DIR="$HOME/.nvm"
    [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \. "$(brew --prefix)/opt/nvm/nvm.sh" # This loads nvm
    [ -s "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
source $(brew --prefix nvm)/nvm.sh
echo "Finish NVM"
echo `date`

# PATH
export PATH="$HOME/bin:$PATH"
export PATH=/usr/local/bin:$PATH
export PATH="~/Library/Python/3.9/bin":$PATH
export PATH="~/Library/Python/3.8/bin":$PATH
