# Terminal Profile
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM="xterm-256color" 
export PS1='\[\e[0;31m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;33m\]\w\[\e[0m\]\n\[\e[1;33m\][\d \t]\[\e[m\]$ '


# ALIASES
alias run_jupyter_notebook="jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --inplace --execute"


# ENVs
